// Auto-generated by build-notes.js
const NOTES_DATA = [
  {
    "id": "reinforcement_learning",
    "title": "Reinforcement Learning",
    "description": "Policy gradients, value functions, actor critic methods, PPO, GRPO, and post training alignment.",
    "notes": [
      {
        "title": "Introduction to Reinforcement Learning",
        "slug": "introduction_to_reinforcement_learning"
      },
      {
        "title": "Policy Gradient Theorem",
        "slug": "policy_gradient_theorem"
      },
      {
        "title": "Post Training",
        "slug": "post_training"
      }
    ]
  },
  {
    "id": "rag",
    "title": "Retrieval Augmented Generation",
    "description": "Sparse/dense retrieval, vector databases, and knowledge augmented generation systems.",
    "notes": [
      {
        "title": "Retrieval Augmented Generation",
        "slug": "retrieval_augmented_generation"
      }
    ]
  },
  {
    "id": "transformers_llms",
    "title": "Transformers & LLMs",
    "description": "Attention mechanisms, scaling laws, KV caching, MoE, quantization, and LLM optimization.",
    "notes": [
      {
        "title": "Transformers",
        "slug": "01_transformers"
      },
      {
        "title": "GPT BERT and BART",
        "slug": "02_gpt_bert_and_bart"
      },
      {
        "title": "KV Caching",
        "slug": "03_kv_caching"
      },
      {
        "title": "Flash Attention",
        "slug": "04_flash_attention"
      },
      {
        "title": "LLM Scaling Laws",
        "slug": "05_llm_scaling_laws"
      },
      {
        "title": "Decoding and Sampling Algorithms",
        "slug": "decoding_and_sampling_algorithms"
      },
      {
        "title": "GPU Optimization",
        "slug": "gpu_optimization"
      },
      {
        "title": "Mixture of Experts",
        "slug": "mixture_of_experts"
      },
      {
        "title": "PEFT",
        "slug": "peft"
      },
      {
        "title": "Quantization",
        "slug": "quantization"
      },
      {
        "title": "RoPE",
        "slug": "rope"
      }
    ]
  },
  {
    "id": "sequence_models",
    "title": "Sequence & Recurrent Models",
    "description": "Recurrent networks, Seq2Seq, LSTMs, GRUs, and recurrent attention mechanisms.",
    "notes": [
      {
        "title": "RNNs",
        "slug": "15_rnns"
      },
      {
        "title": "Sequence to Sequence RNNs",
        "slug": "16_sequence_to_sequence_rnns"
      },
      {
        "title": "LSTM and GRU",
        "slug": "17_lstm_and_gru"
      },
      {
        "title": "Bidirectional RNNs",
        "slug": "18_bidirectional_rnns"
      },
      {
        "title": "Attention in RNNs",
        "slug": "19_attention_in_rnns"
      }
    ]
  },
  {
    "id": "computer_vision",
    "title": "Computer Vision",
    "description": "Convolutional networks, residual architectures, and visual sequence models.",
    "notes": [
      {
        "title": "Convolutional Neural Networks",
        "slug": "13_convolutional_neural_networks"
      },
      {
        "title": "Residual Networks",
        "slug": "14_residual_networks"
      },
      {
        "title": "CRNNs and Advanced Computer Vision",
        "slug": "crnns_and_advanced_computer_vision"
      }
    ]
  },
  {
    "id": "deep_learning",
    "title": "Deep Learning Foundations",
    "description": "Neural networks, activation functions, optimization, normalization, and backpropagation mechanics.",
    "notes": [
      {
        "title": "Neural Networks",
        "slug": "07_neural_networks"
      },
      {
        "title": "Non Linearity and Activation Functions",
        "slug": "08_non_linearity_and_activation_functions"
      },
      {
        "title": "Optimization Algorithms",
        "slug": "09_optimization_algorithms"
      },
      {
        "title": "Backpropagation",
        "slug": "10_backpropagation"
      },
      {
        "title": "Normalization",
        "slug": "11_normalization"
      },
      {
        "title": "Activation Functions",
        "slug": "12_activation_functions"
      },
      {
        "title": "Regularization",
        "slug": "regularization"
      }
    ]
  }
];